### ISSUE TITLE
Question about attribute annotations

### ISSUE THREAD

**Issue by liyuxuan89** [cvdfoundation/fashionpedia#1]
Great dataset !

I have some questioins regarding the attribute annotations. I'm wondering if the attributes is related to the categories. For example, 'classic military (jacket)' should be a subcategory for 'jacket'. But there are attributes like 'hoodie', 'blazer' which don't have any information about how they are related to the categories.  This makes it hard to filter the attribute prediction with the classification result of the category  and determine which categories are mutual exclusive.

Also, it's there a way to get a complete version of this image.
![image](https://user-images.githubusercontent.com/43963025/88373292-2ec56e00-cdca-11ea-8dc9-2b9849d2c774.png)

Any help to solve the above problem will be appreciated.

**Comment by KMnP** [comment]
Thanks for the question. Here we define  'classic military (jacket)'  belong to the "nickname" super-category. Since we include the basic level categories in the apparel categories and leave everything else to attributes.
