### ISSUE TITLE
Question about annotation files

### ISSUE THREAD

**Issue by ousinkou** [cvdfoundation/fashionpedia#2]
I downloaded the instances_attributes_train2020.json and instances_attributes_val2020.json. And I found weird segmentation  format . You can search "counts" in the file. Such as  these rows:

 "segmentation": {
        "size": [
          1024,
          688
        ],
        "counts": "emX8;do02M3M4K4L4L3M4M2M3M4L3M4L3N2B?L3M3]LAhVO[NKU2eh0`0UWOaM3o1\\g0S2WXOUL7j1\\g0j51O001O1O1O001O1N2O0O2O001N101O0O2O0O1O1O1O1O1O1YOgWOfIZh0U6oWOfIRh0X6UXObIlg0]6[XO\\Ifg0b6m0O1N2K5J6\\O]VOeJii0V5c0M3[ObUOdKbj0Z4c0N2N2M3N2J6H8H8I7E;E;E;E;E<G8J6K5J7I7I`0C[Yh:"
      },

Did the file have a problem? Hoping for help.

**Comment by KMnP** [comment]
Hi @ousinkou, those are compressed RLE format, same as the format used in coco API. 

We also state the formats in README.

**Comment by ousinkou** [comment]
> Hi @ousinkou, those are compressed RLE format, same as the format used in coco API.
> 
> We also state the formats in README.

Very thanks. I use coco api, it seems ok now.
