### ISSUE TITLE
What's the difference between this dataset and imaterialist-fashion-2020-fgvc7?

### ISSUE THREAD

**Issue by ousinkou** [cvdfoundation/fashionpedia#3]
I found this dataset is similar with kaggle competition imaterialist-fashion-2020-fgvc7.  The pictures of the two datasets are similar, but the resolution is different, and the label format is different. Can you elaborate on the relationship between these two data sets？

**Comment by KMnP** [comment]
Thanks for noticing the connection to imat-fashion2020. 

We do use Fashionpedia for the imat-fashion challenges for both FGVC6 and FGVC7. We changed the label format to csv to comply with Kaggle platform. And the evaluation metric is different from the Fashionpedia-api. 

Our original idea is to closely follow COCO, and a JSON format is also requested by many participant in iMat-Fashion. You can also find the connection of imat-fashion and Fashionpedia in our [project page.](https://fashionpedia.github.io/home/index.html)

I will close the issue for now. Feel free to reopen it if you have more questions.
