### ISSUE TITLE
Some grayscale images in train set?

### ISSUE THREAD

**Issue by BrandonHanx** [cvdfoundation/fashionpedia#4]
Hi, thanks for your great work.

I found there are many gray-scale images in the training set. Is this expected?

like `ac7f353fd7481926e8fa9eafed609948.jpg`, `7d956f0919f2eab63e481e9321ce2028.jpg` and so on

**Comment by KMnP** [comment]
hey, thanks for the question. Yes that is expected.

**Comment by BrandonHanx** [comment]
Thanks for your reply.

How do you tackle these grayscale images in the training stage? Just repeat 3 channels for CNN's input?

**Comment by KMnP** [comment]
```
from PIL import Image as PILImage
im = PILImage.open(img_dir)
rgb_im = im.convert('RGB')
```

I converted them to rgb using pillow

**Comment by BrandonHanx** [comment]
I see. This issue is solved for me. Thanks.
