### ISSUE TITLE
Semantic Segmentation

### ISSUE THREAD

**Issue by joshmyersdean** [cvdfoundation/fashionpedia#8]
Hello, happy new year, and thank you for this work!

I was wondering if you had any results for semantic segmentation on this dataset or are aware of any works that have such results? 

I appreciate your time.

Thank you!
Josh

**Comment by KMnP** [comment]
Hi Josh, Thanks for your question. I don't know any work doing that off the top of my head. Are you currently working on semantic segmentation? Please let me know the results if you have any! :)

**Comment by joshmyersdean** [comment]
Hi Menglin, thank you for the quick response! We are currently working on using Fashionpedia for semantic segmentation and will definitely let you know when we have some decent results!

**Comment by tgyhhh** [comment]
> 你好，新年快乐，谢谢你的工作！
> 
> 我想知道您对该数据集的语义分割是否有任何结果，或者是否知道有任何具有此类结果的作品？
> 
> 我感谢你的时间。
> 
> 谢谢你！ 乔什
Hello, if this data set is used for semantic segmentation, what are the tags for semantic segmentation in json files? Thank you very much!
